version: "3"

services:
  backend:
    network_mode: host
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/usr/src/savingfinance_backend_dev
      - /usr/src/savingfinance_backend_dev/node_modules

  db:
    network_mode: host
    container_name: savingfinanceDB_dev
    image: mvertes/alpine-mongo
    logging:
      driver: none
