/* groovylint-disable-next-line CompileStatic */
pipeline {
    agent none
    stages {
        stage('Back-end') {
            agent {
                docker { image 'node:14-alpine' }
            }
            steps {
                echo 'mongo image initialized'
            }
        }
    }
}

