/* groovylint-disable-next-line CompileStatic */
pipeline {
    agent none
    stages {
        stage('backendNode') {
            steps {
                echo 'executing node image'
                agent {
                    docker { image 'node:14-alpine' }
                }
            }
        }

        stage('build') {
            steps {
                echo 'executing yarn'
                nodejs('SavingFinanceNode') {
                    sh 'yarn install'
                }
            }
        }
    }
}
