/* groovylint-disable-next-line CompileStatic */
pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                echo 'executing yarn'
                nodejs('SavingFinanceNode') {
                    sh 'yarn install'
                }
            }
        }

        stage('run test') {
            steps {
                echo 'executing test'
                /* groovylint-disable-next-line DuplicateStringLiteral */
                nodejs('SavingFinanceNode') {
                    sh 'yarn test'
                }
            }
        }
    }
}
